seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"
  privileged: true
  environment:
    - GRID_MAX_SESSION=10
    - GRID_TIMEOUT=300000

chromenode:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub
  volumes:
    - "/dev/shm:/dev/shm"
  environment:
    - HEAPSPACE=2g
